# Generated by Django 3.2.19 on 2023-06-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_res_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='res_name',
            new_name='reservation_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time_of_res',
            new_name='time_of_reservation',
        ),
    ]
