# Generated by Django 3.2.19 on 2023-06-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230620_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
