# Generated by Django 3.2.19 on 2023-07-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReservation',
        ),
    ]
